services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=hema
      - POSTGRES_PASSWORD=45086932
      - POSTGRES_DB=db
    ports:
      - 5432:5432
